scylladb/gemini

- cmd/gemini/root.go
- cmd/gemini/schema.go
- schema.go
- store/store.go
A new cli argument `--oracle-replication-strategy` is added to allow
for setting a different replication strategy for the oracle cluster.
It defaults to whatever is set as the test cluster strategy.
Fixes: #220
> schema: optionally apply different replication strategy

- cmd/gemini/root.go
It used to set the incorrect property maxColumns instead of
minColumns.
Fixes: #224
> gemini: min-columns correctly set in CLI

- cmd/gemini/jobs.go
Scylla does not allow dropping a column that is part of a materialized
view. Let's avoid doing DDL operations altogether for such cases to be
safe.
Fixes #230
> gemini: Avoid DDL operations for a table with MV

- schema.go
- schema_test.go
To avoid clashes in index names across tables.
Fixes: #232
> Namespacing index names with table names

- .github/workflows/go.yml
- cmd/gemini/generators.go
- cmd/gemini/jobs.go
- cmd/gemini/pump.go
- cmd/gemini/root.go
- cmd/gemini/spinner.go
- cmd/gemini/status.go
- generator.go
- generator_test.go
- go.mod
- go.sum
- partition.go
- schema.go
- store/cqlstore.go
Using 'golang.org/x/sync/errgroup' instead of Tomb. Simplifying
the nested goroutines and returns errors more frequently.
Fixes: #226
> gemini: attempts to shutdown more precisely

- schema.go
Makes it consistent with how CREATE KEYSPACE and CREATE TABLE statements
are used.
This can be useful, for example, when we want to restart gemini with the same
schema after it was already executed once and we don't want to drop the
existing tables.
> schema: add "IF NOT EXISTS" check when creating a new type

- store/cqlstore.go
- store/store.go
The `newSession` function compared `out` (the tracing output
destination) with `nil` to decide if tracing should be enabled on the
created session.
Although the underlying value of `out` was `nil *os.File`, it was passed
in as `io.Writer`. However, `nil *os.File` is a non-`nil` `io.Writer`,
so the `out != nil` check always passed.
Fixes #247.
> store: don't enable tracing if not requested

- cmd/gemini/jobs.go
As explained by Henrik Johansson:
"If it has a materialized view the lock will be kept in perpetuity since
the code returns without unlocking the lock."
Fix it up.
> Fix mutex unlocking in ddl() function

- schema.go
This pull requests removes recursive "t.mu" table read locks -- which
can deadlock -- from the functions the `GenMutateStmt()` function calls.
Refs #246
> Remove some recursive table read locks

- schema.go
gemini fails if an index already exists (--drop-schema=false)
```
Error: unable to create schema: unable to apply mutations to the test store: [cluster = test, query = 'CREATE INDEX col0_idx ON ks1.table1 (col0)']: Index col0_idx already exists
unable to create schema: unable to apply mutations to the test store: [cluster = test, query = 'CREATE INDEX col0_idx ON ks1.table1 (col0)']: Index col0_idx already exists
```
> Create indexes only if they dont already exist

- cmd/gemini/status.go
Due to issue https://github.com/scylladb/gemini/issues/236
gemini result file could be not created.
Let print the Sample result to stdout if error detected.
This allow to investigate issue while the #236 is not fixed
> Print sample status to stdout if error detected

- schema.go
Gemini could failed with error:
Error: unable to create schema: unable to apply mutations to the test store:
[cluster = test, query = 'CREATE MATERIALIZED VIEW ks1.table1_mv_0 AS SELECT * FROM ks1.table1
WHERE col10 IS NOT NULL AND pk0 IS NOT NULL AND pk1 IS NOT NULL AND pk2 IS NOT NULL AND pk3 IS NOT NULL AND
ck0 IS NOT NULL AND ck1 IS NOT NULL AND ck2 IS NOT NULL PRIMARY KEY ((col10,pk0,pk1,pk2,pk3),ck0,ck1,ck2)']:
Cannot add already existing table "table1_mv_0" to keyspace "ks1"
Add to query "IF NOT EXISTS" "CREATE MATERIALIZED VIEW IF NOT EXISTS %s.%s AS SELECT * FROM %s.%s WHERE %s PRIMARY KEY"
> Fix query create mv

- store/cqlstore.go
Condition statement in load function was wrong - 'err` variable was
never assigned. This caused to ignore cql errors and leading to wrong
validation error message.
This commit fixes variable assignment, so validation error message in
test results is more appropriate.
fixes: https://github.com/scylladb/scylla-cluster-tests/issues/4694
> fix error handling in load function

- inflight/inflight.go
- inflight/inflight_test.go
The reason for this leak is the that golang maps are not shrinking when you do delete on them.
Under the hood, for tracking inflight tokens it is using [u64set](https://github.com/scylladb/go-set/blob/master/u64set/u64set.go) from [go-set](https://github.com/scylladb/go-set) which is based on map.
key for which is every token gemini is addressing, no wonder it is leaking memory.
Solution is to shrink map ocassionaly
> Fix issue #267

- cmd/gemini/jobs.go
- cmd/gemini/status.go
There are two issues combined together can lead to make warmup spinning forever:
- It does not respect failFast
- it does not increase i, and as result where sending results on every operation
As result, when error is faced, `sampleStatus` is bailing out after receiving first error, but `warmup` sitll spinning.
Every next result it submits to result channel, after `10000` iterations result channel is full and next time when `warmup` submits record to the result channel it is getting stuck and never comeback.
This PR also contains non-functional, cosmetic changes to bump readability
> Fix warmup hunging

- Makefile
- inflight/inflight.go
- inflight/inflight_test.go
Reduce memory foot print for `inflight` registry by using `struct{}` instead of `bool`
Also add test for shrinking
> fix(inflight): reduce memory footprint by using struct{} instead of bool

- cmd/gemini/jobs.go
- cmd/gemini/root.go
- columns.go
- datautils.go
- generator.go
- schema.go
- types.go
Part of #298, addressed following issues:
1. `PartitionRangeConfig` is passed all way down as struct, which makes golang to allocate memory for it on multiple times for every iteration
2.  `ValueWithToken` is passed all way down as struct, which makes golang to allocate memory for it on multiple times for every iteration
> fix(schema): delivery values and partition range config as pointers

- cmd/gemini/jobs.go
- generator.go
- generator_test.go
- partition.go
- schema.go
Part of https://github.com/scylladb/gemini/issues/298
1. Convert generator methods to use pointer receiver
2. Optimize PK values turnover
3. Convert channels to pointers
> fix(generator): reduce memory allocations

- inflight/inflight.go
Part of https://github.com/scylladb/gemini/issues/298
Inflights are initialized per partition, so limit of `1000000` makes no sense
> fix(inflight): reduce shrinking limit

- store/helpers.go
For example in this function compare for int8:
```
case int8:
mjs, _ := mj["pk0"].(int8)
return mis < mjs
```
Code:
```
x := big.NewInt(1)
y := big.NewInt(10)
fmt.Println(x.Cmp(y) < 0)
//Output:true
```
> lt function have wrong compare for big.Int

- cmd/gemini/jobs.go
- DDL should execute `postStmtHook` only when all DDL statements are executed successfully 
- DDL should return on err right away
> fix(ddl): make it handle error properly

- schema.go
*fixed generation not nil stmt with nil values in genSinglePartitionQuery.
> fix(genSinglePartitionQuery) It should generate stmt with not nil values

- cmd/gemini/root.go
Oracle cluster use fixed request timeout 120s, while test cluster user configurable request timeout provided by --request-timeout parameter. This cause request time for queries to oracle cluster for MV, SI.
Set same parameter for Oracle cluster
> fix(root.createClusters): Use request-timeout parameter for Oracle

- pkg/coltypes/simple_type.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Results:
```
pkg: github.com/scylladb/gemini/pkg/utils
cpu: 12th Gen Intel(R) Core(TM) i9-12900HK
BenchmarkUtilsRandStringNew100
BenchmarkUtilsRandStringNew100-20     	 9158696	       157.4 ns/op
BenchmarkUtilsRandStringNew1000
BenchmarkUtilsRandStringNew1000-20    	 2407350	       592.3 ns/op
BenchmarkUtilsRandStringOld100
BenchmarkUtilsRandStringOld100-20      	 1878685	       666.5 ns/op
BenchmarkUtilsRandStringOld1000
BenchmarkUtilsRandStringOld1000-20     	  174566	      6064 ns/op
PASS
```
> fix(utils): speedup random string generation

- pkg/builders/builders.go
- pkg/coltypes/bag.go
- pkg/coltypes/simple_type.go
- pkg/coltypes/tuple.go
- pkg/coltypes/types.go
- pkg/coltypes/udt.go
- pkg/generators/schema_mutation_stmt_test.go
- pkg/generators/statement_generator.go
- pkg/generators/suite_utils_test.go
- pkg/generators/test_expected_data/insert.json
- pkg/generators/test_expected_data/update.json
- pkg/querycache/querycache.go
- pkg/status/status_test.go
- pkg/testschema/columns.go
- pkg/testschema/table.go
- pkg/typedef/typedef.go
- pkg/typedef/typedef_test.go
- pkg/utils/undertest.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Every time we generate an operation we recreate statemet. 
Since some of the statement content could be cached we need to do that in sake of speeding things up.
> feat(generators): impelemt statement cache

- pkg/generators/column.go
- pkg/generators/statement_generator.go
- pkg/jobs/gen_check_stmt.go
- pkg/jobs/gen_utils_test.go
- pkg/typedef/columns_test.go
- pkg/typedef/typedef.go
'IndexDef' refers to table column by arrays id :
```
IndexDef struct {
...
ColumnIdx int    `json:"column_idx"`
}
```
And it is used like this:
```
for i := 0; i < idxCount; i++ {
builder = builder.Where(qb.Eq(t.Indexes[i].Column))
values = append(values, t.Columns[t.Indexes[i].ColumnIdx].Type.GenValue(r, p)...)
typs = append(typs, t.Columns[t.Indexes[i].ColumnIdx].Type)
}
```
For example: If column with id=0 will be deleted and  'IndexDef' use column with id>0, as result - incorrect queries with 'IndexDef'.
> fix(IndexDef): it should refer directly to index table column

- pkg/jobs/gen_ddl_stmt.go
- pkg/jobs/gen_ddl_stmt_test.go
- pkg/typedef/columns.go
- pkg/typedef/columns_test.go
- pkg/typedef/table.go
Scylla don`t allow to drop column that is part of any materialized view primary key.
Same for column that is used in any type of index.
We need to exclude these columns from list of columns that could be deleted.
> fix(GenDDLStmt) column drops should be with conditions

- pkg/jobs/jobs.go
- pkg/store/cqlstore.go
- pkg/store/store.go
> fix(jobs): make them finish test properly when it is stopped

- cmd/gemini/root.go
- cmd/gemini/schema.json
- cmd/gemini/strategies_test.go
- pkg/generators/column.go
- pkg/generators/column_generator.go
- pkg/generators/statement_generator.go
- pkg/generators/table.go
- pkg/jobs/gen_check_stmt.go
- pkg/jobs/gen_ddl_stmt.go
- pkg/jobs/gen_mutate_stmt.go
- pkg/jobs/gen_utils_test.go
- pkg/jobs/jobs.go
- pkg/querycache/querycache.go
- pkg/typedef/bag.go
- pkg/typedef/columns.go
- pkg/typedef/columns_test.go
- pkg/typedef/table.go
- pkg/typedef/tuple.go
- pkg/typedef/typedef.go
- pkg/typedef/types.go
- pkg/typedef/types_test.go
- pkg/typedef/udt.go
issue #353.
Added 'complex_type' for all complex types of columns.
Redid columns 'UnmarshalJSON'.
Now complex type column description in JSON looks like it:
```
{
"name": "col5",
"type": {
"complex_type": "tuple",
"coltypes": [
"varchar",
"smallint"
],
"frozen": false
}
```
Before can`t see complex type that is describe:
```
{
"name": "col5",
"type": {
"coltypes": [
"varchar",
"smallint"
],
"frozen": false
}
```
> Redo columnDef.UnmarshalJSON

- pkg/typedef/errors.go
- pkg/typedef/schema_test.go
- pkg/typedef/schemaconfig.go
fixed error:
```
if sc.MaxColumns <= sc.MinClusteringKeys {
return ErrSchemaConfigInvalidCols
}
```
renamed errors. Sample:
ErrSchemaConfigInvalidCols >>>ErrSchemaConfigInvalidRangeCols
> fix(SchemaConfig) Valid() - fix errors

- pkg/store/store.go
> fix(Check) skip processing 0 rows responses

- pkg/store/helpers.go
Currently 'nil' come results panic:
```
{"L":"INFO","T":"2023-06-21T10:55:08.476-0400","N":"work cycle.validation_job","M":"Retring failed validation. 1 attempt from 10 attempts. Error: row count differ (test has 59 rows, oracle has 60 rows, test is missing rows: [pk16=45604486-11-25 23:27:42.51 +0000 UTC, \tpk17=3h50m24.065357675s, \tpk18=2130-04-03 00:00:00 +0000 UTC, \tpk19=52d8145cd62ff63, \tck=1829966953], oracle is missing rows: [])"}
{"L":"INFO","T":"2023-06-21T10:55:09.348-0400","N":"work cycle.validation_job","M":"ending validation loop"}
panic: unhandled type <nil>
```
> fix(store) add nil processing in lt function

- .gitignore
- pkg/generators/generator.go
- pkg/generators/partition.go
Previous implementation suffers couple issues:
- It is not logical to pause generator on channel wait only when we
already know that we need more values. As in:
```
if g.partitions.NeedMoreValues() {
g.waitForMoreValuesNeeded()
}
```
- Wakeup call was placed in Get() function while consumption is done in
a loop inside, in a pick() function, this can theoretically lead to a
deadlock
- Small nit: hardcoded cap(s.values)-30, in theory channel can be
smaller than 30
- When generator wakes up it fills partitions until it blocks on
a first full, this doesn't say anything about whether others
are filled or not. Especially when imbalanced situation happens
such as most partitions are full and one empty then single wake up call
has relatively small chance to fill this partition until it blocks. …
> fix(generator): rework waking up generator to avoid unpredictable behavior

- pkg/store/cqlstore.go
- pkg/store/store.go
Retry inserting a list value will produce duplicated list elements in Scylla when done with the same timestamp.
Fixes https://github.com/scylladb/scylladb/issues/7937
> fix(store): retry with new timestamp value

- cmd/gemini/root.go
- cmd/gemini/schema.go
- cmd/gemini/strategies_test.go
- pkg/generators/column_generator.go
- pkg/generators/statement_generator.go
- pkg/generators/statement_generator_test.go
- pkg/jobs/gen_ddl_stmt.go
- pkg/replication/replication.go
- pkg/tableopts/options.go
- pkg/typedef/columns.go
- pkg/typedef/columns_test.go
- pkg/typedef/schema_test.go
- pkg/typedef/simple_type.go
- pkg/typedef/test_expected_data/full_schema.json
- pkg/utils/utils.go
Us solution https://github.com/scylladb/gemini/issues/379#issue-1789958196
Included dk/370-gemini-generates-mutations-non-deterministically 
Added full schema and test for it.
Added test for generate schems from 10 different seeds.
Fixed some bugs on this way.
> add(typedef,generators) schema tests add

- pkg/store/store.go
As solution issue https://github.com/scylladb/gemini/issues/365.
Added simple logic to synchronize identical queries on "testStore" and oracalStore'.
As results:
1) Time difference between Stmt start on 'testStore' and 'oracalStore' is 10-300μs, before was from 350-20000μs
2) Productivity has increased by about 30%
3) Repeats on queries with big responses gone away.
> add(store): queries syncer

- pkg/utils/utils.go
The `time` CQL type represents a duration of less than 24 hours, represented as `int64_t nanoseconds`:
https://github.com/apache/cassandra/blob/f5df4b219e063cb24b9cc0c22b6e614506b8d903/doc/native_protocol_v4.spec#L941
```
6.16 time
An 8 byte two's complement long representing nanoseconds since midnight.
Valid values are in the range 0 to 86399999999999
```
`time` is an `int64` in range `[0;86399999999999]`, values outside of this range are invalid.
`RandTime()` generated values using `rnd.Int63()`, but this generates values outside of the allowed range.
Let's fix it so that it generates values in the correct range.
The generation of `time` values was recently modified in https://github.com/scylladb/gemini/pull/359, and `time` values have been enabled in tests, but this caused failures on …
> fix(utils): generate time values in the correct range

- cmd/gemini/root.go
Statement data and schema seed are the same at the moment.
We need to split them in order to be able to run different data flow on the same schema
> feat(root): introduce schema-seed

- pkg/store/store.go
Check function works extremely slow then responses has not nil data.
You can see this if compare read operations count with warmup and without warmup on same schema. It's related with fill oldValues chans during warmup.
Or if you try to force validations only with oldValues chans.
reflect.DeepEqual works up to 10 times faster that old logic with sort rows and diff generation.
And no need to sort rows and to try generate diff in cases with same testRows and oracleRows.
> fix(store): add simple compare in Check function to avoid complex diff generation

- pkg/jobs/gen_check_stmt.go
Us part of solution https://github.com/scylladb/gemini/issues/354#issue-1753683701.
At this moment PK processig logic in  genMultiplePartitionQuery funcs :
```
for i, pk := range t.PartitionKeys {
builder = builder.Where(qb.InTuple(pk.Name, numQueryPKs))
for j := 0; j < numQueryPKs; j++ {
vs := g.GetOld()
if vs == nil {
return nil
}
values = append(values, vs.Value[i])
typs = append(typs, pk.Type)
}
```
Which leads to generate stmt`s with failed PK values combinations and exhaust oldValues channels in generators.
As result or this PR - count of responses with nil rows decreased on 20%.
> fix(jobs): fix wrong PK processing logic in genMultiplePartitionQuery funcs

- cmd/gemini/generators.go
- cmd/gemini/root.go
- pkg/generators/generator.go
- pkg/generators/partition.go
- pkg/realrandom/source.go
- pkg/typedef/bag.go
- pkg/typedef/columns.go
- pkg/typedef/interfaces.go
- pkg/typedef/schema.go
- pkg/typedef/simple_type.go
- pkg/typedef/tuple.go
- pkg/typedef/types.go
- pkg/typedef/udt.go
There is a problem that leads to gemini being stuck, due to unability of generator to hit certain partitions.
It happens when partition columns size is too small for murmur to get 100% partition coverage.
There are multiple ways to fix that, but easiest is to calculate pk columns sizes and reduce partition count to match it.
> fix(generators): limit partitions count when size ot pk is too small

- pkg/typedef/columns.go
- pkg/typedef/interfaces.go
- pkg/typedef/tuple.go
- pkg/typedef/udt.go
There is a bug in `ValueVariationsNumber` that makes it return 0 all the time.
Closes #401
> fix(typedef): ValueVariationsNumber returns zero all the time

- cmd/gemini/root.go
- pkg/generators/statement_generator.go
- pkg/jobs/jobs.go
- pkg/stmtlogger/filelogger.go
- pkg/store/cqlstore.go
- pkg/store/store.go
- pkg/typedef/bag.go
- pkg/typedef/const.go
- pkg/typedef/interfaces.go
- pkg/typedef/simple_type.go
- pkg/typedef/tuple.go
- pkg/typedef/typedef.go
- pkg/typedef/types.go
- pkg/typedef/types_test.go
- pkg/typedef/udt.go
- pkg/utils/utils.go
Fixes #409 
Adds option to log statements flow
Resulted file looks like:
```
DROP KEYSPACE IF EXISTS ks1;
CREATE KEYSPACE IF NOT EXISTS ks1 WITH REPLICATION = {'class':'SimpleStrategy','replication_factor':'1'};
CREATE TYPE IF NOT EXISTS ks1.udt_3644515473 (udt_3644515473_0 bigint,udt_3644515473_1 blob);
CREATE TYPE IF NOT EXISTS ks1.udt_62666315 (udt_62666315_0 inet,udt_62666315_1 boolean,udt_62666315_2 date,udt_62666315_3 float,udt_62666315_4 float,udt_62666315_5 text,udt_62666315_6 timeuuid);
CREATE TYPE IF NOT EXISTS ks1.udt_1679318000 (udt_1679318000_0 time,udt_1679318000_1 ascii,udt_1679318000_2 inet,udt_1679318000_3 smallint,udt_1679318000_4 bigint);
CREATE TABLE IF NOT EXISTS ks1.table1 (pk0 text,pk1 bigint,pk2 uuid,ck0 blob,ck1 smallint,ck2 varchar,col0 frozen<map<date,int>>,col1 …
```
> feat(cli): add statement-log-file option

- pkg/stmtlogger/filelogger.go
- pkg/store/cqlstore.go
- pkg/store/store.go
Empty 'test-statement-log-file' option brings to panic.
Reason:
```
func NewFileLogger(filename string) (StmtToFile, error) {
if filename == "" {
return nil, nil
...
```
```
func (fl *fileLogger) LogStmt(stmt *typedef.Stmt) {
ch := fl.activeChannel.Load()
...
```
> fix(stmtlogger): lets gemini work with empty 'test-statement-log-file' option

- cmd/gemini/root.go
- cmd/gemini/schema.go
- pkg/generators/statement_generator.go
- pkg/typedef/schemaconfig.go
There is a crash in gemini, which is deeped then we expected first, and it comes down to the materialized views generation and validation. Something there is wrong, until further investigation (and possibly gemini redisign, this issue cannot be fixed). As I've discussed with @fruch about this issue, we concluded that the best way forward for now is to disable materialized views until the redisign of the project.
Simplest solution is just to add the CLI flag and propagate it to the creation of the materialized views.
Jenkins Issue: https://jenkins.scylladb.com/job/enterprise-2024.1/job/gemini-/job/gemini-3h-with-nemesis-test/27/
> feature(materialized-views): add cli flags to disable materialized views

- .github/workflows/release.yml
- .goreleaser.yml
In order to make use of goreleaser, we need GitHub Action to build and `gemini` and generate changelog
This is the action to do so. 
Inside the repository, we don't have any AWS Keys to upload gemini binaries to S3 Bucket. until that gets sorted out, it is better to leave it commented and have the gemini release as soon as possible to test the #424 in SCT.
> feature(ci): release gemini using goreleaser and github actions

- .golangci.yml
- cmd/gemini/generators.go
- pkg/generators/statement_generator.go
- pkg/generators/statement_generator_test.go
- pkg/generators/table.go
- pkg/jobs/gen_check_stmt.go
- pkg/jobs/gen_utils_test.go
- pkg/querycache/querycache.go
- pkg/store/cqlstore.go
- pkg/store/helpers.go
- pkg/tableopts/options.go
- pkg/testutils/name_mappings.go
- pkg/typedef/columns_test.go
- pkg/typedef/types_test.go
- pkg/utils/utils.go
1. Update GolangCI configration for validate all files when run in GH Action
2. Fix files to be correct according to the `.golangci` rules
> fix(lints): all gemini lint warning fixes -> as per current golangci rules

- .github/workflows/docker.yml
- .github/workflows/dockerhub-description.yml
- .github/workflows/go.yml
- .github/workflows/integration-tests.yml
- .github/workflows/release.yml
- Makefile
When running multiple ScyllaDB instances on the same machine (especially in docker), it can fail to start due to the `fs.aio-max-nr` kernel setting being too low. This makes our `Integration Tests` unstable and many times tests are being aborted due to Scylla never starting.
Since Github `ubuntu-latest` will be moving to `24.04` and this fix for some reason does not work on `latest` (didn't investigate why) upgrade to `24.04` is necessary (and it it is proven to work on `24.04`)
- https://github.com/scylladb/gemini/actions/runs/12238934057/job/34138199744
- https://github.com/scylladb/gemini/actions/runs/12076017914/job/33676763946
> fix(scylla): failed to start scylla due to fs.aio limit

- Makefile
- cmd/gemini/root.go
- go.mod
- pkg/metrics/metrics.go
- pkg/stmtlogger/filelogger.go
- pkg/store/store.go
> feature(compression): add zstd log compression to statement log files

- pkg/stmtlogger/filelogger.go
- pkg/stmtlogger/filelogger_test.go
Just writing to file when compression is enabled, memory leak, cause logging to file with compression is done in memory.
Also by not flushing data to file, it it bound to lose some statements needed for debugging. so everything must be logged fully.
To validate this behavior, tests and benchmarks have been added to future-proof this feature
> fix(filelogger): fixing issue with writting and flushing data to file

- .gitignore
- Makefile
- docker/docker-compose-scylla-cluster.yml
- docker/monitoring/Gemini.json
- docker/monitoring/scylla_servers.yml
- docs/development.md
- Adding Grafana dashboard for `gemini` specific metrics (this could be ported to SCT)
- Adding Documentation for gemini's development (running scylla cluster, running integration tests, running unit tests, building, and loading grafana dashboard)
> feature(tests): add grafana dashboard with gemini specific  metrics

- pkg/store/cqlstore.go
session.Bind() with a callback doesn't populate the query.values field that the Observer sees. This was preventing from values being populated in statement loggers.
fixes: https://github.com/scylladb/gemini/issues/532
> fix(cqlstore): fix query binding to have values in observers

- .github/instructions.md
- .github/workflows/go.yml
- .github/workflows/integration-tests.yml
- .github/workflows/release.yml
- .golangci.yml
- Dockerfile
- Makefile
- go.mod
- pkg/generators/partition.go
- pkg/joberror/joberror_test.go
- pkg/services/workload_test.go
- pkg/testutils/scylladb.go
During the upgrade to Go 1.25, it showed that we have a `data race` in `partitions` still, even with all fancy features and `data race` inside `test containers` for `random number generation`
> feature(go): use go1.25 everywhere
